import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const walsheim = localFont({
  src: "../assets/fonts/GTWalsheimPro-Medium.woff2",
  variable: "--font-walsheim",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${walsheim.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
